export const MOSTRAR_TITULARES = "MOSTRAR_TITULARES";
export const MOSTRAR_TITULAR = "MOSTRAR_TITULAR";
export const BUSCAR_TITULAR = "BUSCAR_TITULAR";
export const AGREGAR_TITULAR = "AGREGAR_TITULAR";
export const EDITAR_TITULAR = "EDITAR_TITULAR";
export const ELIMINAR_TITULAR = "ELIMINAR_TITULAR";

export const MOSTRAR_ADHERENTES = "MOSTRAR_ADHERENTES";
export const MOSTRAR_ADHERENTESTITULAR = "MOSTRAR_ADHERENTESTITULAR"
export const MOSTRAR_ADHERENTE = "MOSTRAR_ADHERENTE";
export const AGREGAR_ADHERENTE = "AGREGAR_ADHERENTE";
export const EDITAR_ADHERENTE = "EDITAR_ADHERENTE";
export const ELIMINAR_ADHERENTE = "ELIMINAR_ADHERENTE";