// TITULARES
export const MOSTRAR_TITULARES = "MOSTRAR_TITULARES";
export const MOSTRAR_TITULAR = "MOSTRAR_TITULAR";
export const BUSCAR_TITULAR = "BUSCAR_TITULAR";
export const AGREGAR_TITULAR = "AGREGAR_TITULAR";
export const EDITAR_TITULAR = "EDITAR_TITULAR";
export const BAJA_TITULAR = "ELIMINAR_TITULAR";
export const ULTIMO_CONTRATO_TITULAR = "ULTIMO_CONTRATO_TITULAR";


// ADHERENTES
export const MOSTRAR_ADHERENTES = "MOSTRAR_ADHERENTES";
export const MOSTRAR_ADHERENTESTITULAR = "MOSTRAR_ADHERENTESTITULAR"
export const MOSTRAR_ADHERENTE = "MOSTRAR_ADHERENTE";
export const AGREGAR_ADHERENTE = "AGREGAR_ADHERENTE";
export const EDITAR_ADHERENTE = "EDITAR_ADHERENTE";
export const BAJA_ADHERENTE = "BAJA_ADHERENTE";

// PAGOS
export const MOSTRAR_PAGOS = "MOSTRAR_PAGOS";


// PAGOS BCO
export const MOSTRAR_PAGOBCO = "MOSTRAR_PAGOBCO";

// MEMOS
export const MOSTRAR_MEMOS = "MOSTRAR_MEMOS";
export const ULTIMO_MEMO = "ULTIMO_MEMO";
export const AGREGAR_MEMO = "AGREGAR_MEMO";

//HISTORIA
export const MOSTRAR_HISTORIA = "MOSTRAR_HISTORIA";

//FICHAS
export const CAMBIAR_TITULAR = "CAMBIAR_TITULAR";
export const REGISTRAR_VIEJO_TITULAR = "REGISTRAR_VIEJO_TITULAR";

