export const localidades = [
  { value: 4640, label: "ABRA PAMPA" },
  { value: 4600, label: "ALTO COMEDERO" },
  { value: 4608, label: "ALTO VERDE" },
  { value: 4501, label: "ARROYO COLORADO" },
  { value: 4522, label: "BARRO NEGRO" },
  { value: 4608, label: "BORDO LA ISLA" },
  { value: 4516, label: "CAIMANCITO" },
  { value: 4612, label: "CARAHUNCO" },
  { value: 4603, label: "CATAMONTAÑA" },
  { value: 4605, label: "CEIBAL" },
  { value: 4612, label: "CENTRO FORESTAL" },
  { value: 4608, label: "CHAMICAL" },
  { value: 4653, label: "CIENEGUILLAS" },
  { value: 4603, label: "EL CARMEN" },
  { value: 4501, label: "EL PIQUETE" },
  { value: 4506, label: "FRAILE PINTADO" },
  { value: 4630, label: "HUMAHUACA" },
  { value: 4522, label: "LA MENDIETA" },
  { value: 4650, label: "LA QUIACA" },
  { value: 4512, label: "LEDESMA" },
  { value: 4512, label: "L.G.SAN MARTIN" },
  { value: 4616, label: "LOZANO" },
  { value: 4622, label: "MAIMARA" },
  { value: 4608, label: "MUÑAYOC" },
  { value: 4501, label: "PALMA SOLA" },
  { value: 4612, label: "PALPALA" },
  { value: 4608, label: "PERICO" },
  { value: 4605, label: "SAN ANTONIO" },
  { value: 4606, label: "PUESTO VIEJO" },
  { value: 4618, label: "PURMAMARCA" },
  { value: 4601, label: "REYES" },
  { value: 4500, label: "RODEITOS" },
  { value: 4500, label: "SAN PEDRO" },
  { value: 4600, label: "S.S. DE JUJUY" },
  { value: 4608, label: "SANTO DOMINGO" },
  { value: 4624, label: "TILCARA" },
  { value: 4600, label: "TILQUIZA" },
  { value: 4616, label: "VOLCAN" },
  { value: 4616, label: "YALA" },
  { value: 4501, label: "SANTA CLARA" },
  { value: 4513, label: "SANTA BARBARA" },
  { value: 4503, label: "LA ESPERANZA" },
  { value: 4601, label: "RIO BLANCO" },
  { value: 4501, label: "PUESTO NUEVO" },
  { value: 4506, label: "CHALICAN" },
  { value: 4626, label: "HUACALERA" },
  { value: 4616, label: "LEON" },
  { value: 4503, label: "LOTE PARAPETI" },
  { value: 4522, label: "LOTE SAUZAL" },
  { value: 4513, label: "PAMPICHUELA" },
  { value: 4501, label: "REAL DE LOS TOR" },
  { value: 4641, label: "SUSQUES" },
  { value: 4618, label: "TUMBAYA" },
  { value: 4518, label: "YUTO" },
  { value: 4501, label: "EL ARENAL" },
  { value: 4644, label: "CANGREJILLOS" },
  { value: 4603, label: "EL CHUCUPAL" },
  { value: 4522, label: "LOTE DON EMILIO" },
  { value: 4513, label: "VALLE GRANDE" },
  { value: 4655, label: "SANTA CATALINA" },
  { value: 4643, label: "RINCONADA" },
  { value: 4608, label: "MONTERRICO" },
  { value: 4606, label: "PAMPA BLANCA" }
];

export const obra_social = [
  { value: 1, label: "O.S.P.A." },
  { value: 2, label: "O.S.D.E." },
  { value: 3, label: "I.S.S.B." },
  { value: 4, label: "I.O.S.E." },
  { value: 5, label: "O.S.P.A.D." },
  { value: 6, label: "O.S.P.S.P." },
  { value: 7, label: "O.S.P.L.A.D." },
  { value: 8, label: "O.S.T.E.L." },
  { value: 9, label: "O.S.P.R.E.R.A." },
  { value: 10, label: "O.S.P.S.A./A.T.S.A." },
  { value: 11, label: "S.CH.C.J." },
  { value: 12, label: "I.S.J." },
  { value: 49, label: "AMPI" },
  { value: 13, label: "P.A.M.I." },
  { value: 14, label: "O.S.E.C.A.C." },
  { value: 55, label: "OTRA O/S" },
  { value: 15, label: "COSALUD" },
  { value: 16, label: "OSFFENTOS" },
  { value: 17, label: "S.A.T." },
  { value: 18, label: "O.S.P.E.D.U.C." },
  { value: 19, label: "D.I.B.A." },
  { value: 20, label: "SALUD JUJUY" },
  { value: 21, label: "O.S.B.A." },
  { value: 22, label: "A.T.S.A." },
  { value: 23, label: "U.T.A." },
  { value: 24, label: "U.P.C.N." },
  { value: 30, label: "MEDICINA PRIVADA" },
  { value: 25, label: "O.S.P.A.T." },
  { value: 26, label: "AGUA Y ENERGIA" },
  { value: 27, label: "O.S.P.I.L." },
  { value: 28, label: "O.S.P.A.H.G." },
  { value: 29, label: "BOREAL" },
  { value: 41, label: "JERARQUICOS SALUD" },
  { value: 35, label: "PROFEJU" },
  { value: 36, label: "MEDICUS" },
  { value: 37, label: "O.S.P.T.A." },
  { value: 38, label: "O.S.F.A.T.U.N" },
  { value: 39, label: "I.O.S.E." },
  { value: 40, label: "OSMEDICA" },
  { value: 42, label: "ASE MEDIFE S.A." },
  { value: 43, label: "UTEDIC" },
  { value: 44, label: "O.S.P.E." },
  { value: 46, label: "SOS SAN BERNARDO" },
  { value: 45, label: "SOS TUCUMAN" },
  { value: 47, label: "WERCHOW SERV. SOC." },
  { value: 48, label: "PARTICULAR" },
  { value: 50, label: "DOSUBA" },
  { value: 51, label: "O.S.PE.C." },
  { value: 52, label: "OSPAGA/SUTIAGA" },
  { value: 53, label: "FUNDACION DAR" },
  { value: 54, label: "OSETRA" },
  { value: 57, label: "POLICIA FEDERAL" },
  { value: 58, label: "OSPERYHRA" },
  { value: 59, label: "OSDOP" },
  { value: 60, label: "OSPIDA" },
  { value: 61, label: "SWISS MEDICAL" },
  { value: 62, label: "FATFA" },
  { value: 63, label: "OSPIM" },
  { value: 64, label: "AMUR" },
  { value: 65, label: "SAL/OSDEL" },
  { value: 66, label: "PODER JUDICIAL" },
  { value: 67, label: "OSMATA" },
  { value: 68, label: "ACCORD SALUD" },
  { value: 69, label: "QUALITAS" },
  { value: 70, label: "O.S.P.E.S." },
  { value: 71, label: "ACA SALUD" },
  { value: 72, label: "SMATA" },
  { value: 73, label: "CRECER SALUD" },
  { value: 74, label: "O.S.SEG." },
  { value: 75, label: "CRS" },
  { value: 76, label: "SEMESPORT" },
  { value: 77, label: "OSDEPYM" },
  { value: 78, label: "O.S.U.T.GRA" },
  { value: 79, label: "SANCOR SEGURO" },
  { value: 80, label: "U.O.C.R.A." }
];

export const grupos = [
  { value: 2, label: "INSTITUTO DE SEGUROS DE JUJUY" },
  { value: 1002, label: "C.A.B.N.A." },
  { value: 6, label: "POLICIA DE LA PROVINCIA" },
  { value: 1000, label: "COBRADORES" },
  { value: 7, label: "A.PER.JU. (RENTAS)" },
  { value: 8, label: "SINDICATO DE OBRAS SANITARIAS" },
  { value: 12, label: "A.P.UN.JU." },
  { value: 1012, label: "TELEFONICA PALPALA" },
  { value: 1014, label: "COOP. TRIST. JUAREZ MATORRAS" },
  { value: 1022, label: "APEL" },
  { value: 1026, label: "PANAMERICANO" },
  { value: 1031, label: "C.E.D.E.M.S." },
  { value: 16, label: "MUNICIPALIDAD FRAILE PINTADO" },
  { value: 3, label: "A.PE.T.C.R.A." },
  { value: 1035, label: "LA SEVILLANITA" },
  { value: 1036, label: "M.U.T.E.J." },
  { value: 1039, label: "MUNICIPALIDAD DE PERICO" },
  { value: 1043, label: "FRANCISCO MONTIEL" },
  { value: 1044, label: "EMPRESA GRAL. SAVIO" },
  { value: 1045, label: "A.J.P.J. - ASOC.JUDICIAL PROV." },
  { value: 1050, label: "MUNICIPALIDAD DE LA ESPERANZA" },
  { value: 1051, label: "MUNICIPALIDAD DE LA MENDIETA" },
  { value: 1058, label: "A.M.E.T." },
  { value: 1073, label: "ALBERDI S.A." },
  { value: 1077, label: "TACITA DE PLATA" },
  { value: 1080, label: "ADIUNJU" },
  { value: 1082, label: "A.T.S.A. ADMINISTRAC. PUBLICA" },
  { value: 2000, label: "SIN CARGO" },
  { value: 1092, label: "S.E.O.M." },
  { value: 1094, label: "A.P.U.A.P." },
  { value: 1095, label: "AMPERPAG" },
  { value: 1209, label: "CLUB HIDRAULICA" },
  { value: 1212, label: "A.P.A (ASOC.PERS.ARQUITECTURA)" },
  { value: 1213, label: "PANIF.SAN MARTIN" },
  { value: 1214, label: "CO.T.E.JU LTDA." },
  { value: 1215, label: "INSTITUTO DE VIVIENDAS JUJUY" },
  { value: 1216, label: "SUBOFICIALES.RET.PENITENCIARIA" },
  { value: 1219, label: "SI.TRA.V.I.P.-JUJUY" },
  { value: 1224, label: "MUTUAL BANCO PROVINCIA" },
  { value: 1225, label: "A.M.P.M.P." },
  { value: 1248, label: "AMTE" },
  { value: 1254, label: "ACISEPA" },
  { value: 1257, label: "PANADERIA REYES" },
  { value: 1401, label: "A.T.S.A. SANATORIOS PRIVADOS" },
  { value: 1402, label: "A.T.S.A. INS.PCIAL.PREV.SOCIAL" },
  { value: 1010, label: "ING. RIO GRANDE LA MENDIETA" },
  { value: 1500, label: "BAJAS DE CONVENIOS A RECUPERAR" },
  { value: 1100, label: "MUNICIPALIDAD DE MONTERRICO" },
  { value: 1101, label: "FINCA EL PONGO" },
  { value: 2004, label: "FORESTAL NORTEÑA" },
  { value: 1260, label: "CIRCULO RETIRADOS POLICIA PCIA" },
  { value: 1261, label: "A.P.O.P.S." },
  { value: 5002, label: "INST.DE SEGUROS DE JUJUY (Bco)" },
  { value: 5005, label: "SERV. PENITENCIARIO (Bco)" },
  { value: 5006, label: "POLICIA DE LA PROVINCIA (Bco)" },
  { value: 5007, label: "A.PER.JU. (RENTAS) (Bco)" },
  { value: 5008, label: "AGUA DE LOS ANDES  (BCO)" },
  { value: 5012, label: "A.P.UN.JU. (Bco)" },
  { value: 5015, label: "MUNIC. DE SAN PEDRO (Bco)" },
  { value: 5016, label: "MUNIC. FRAILE PINTADO (Bco)" },
  { value: 5017, label: "HOSP. DE FRAILE PINTADO (Bco)" },
  { value: 5018, label: "MUNIC. DE PALMA SOLA (Bco)" },
  { value: 5019, label: "HOSPITAL DE PALMA SOLA (Bco)" },
  { value: 5003, label: "A.PE.T.C.R.A. (Bco)" },
  { value: 6012, label: "TELEFONICA PALPALA (Bco)" },
  { value: 6014, label: "COOP.TRIST. J.MATORRAS (BCO)" },
  { value: 6015, label: "ACEROS ZAPLA (SOEAZ) (Bco)" },
  { value: 6039, label: "MUNIC.DE PERICO (Bco)" },
  { value: 6043, label: "FRANCISCO MONTIEL (Bco)" },
  { value: 6044, label: "EMPRESA GRAL. SAVIO (Bco)" },
  { value: 6045, label: "A.J.P.J.-AS.JUDICIAL PROV(Bco)" },
  { value: 6046, label: "C.P.A.G.I.A.Y T.DE J. (Bco)" },
  { value: 6047, label: "TRANSPORTE ROC (Bco)" },
  { value: 6050, label: "MUNIC. DE LA ESPERANZA (Bco)" },
  { value: 6051, label: "MUNIC.DE LA MENDIETA (Bco)" },
  { value: 6058, label: "A.M.E.T. (Bco)" },
  { value: 6067, label: "MUNIC. DE SANTA CLARA (Bco)" },
  { value: 6068, label: "COM. MUN. DE ARRAYANAL (Bco)" },
  { value: 6082, label: "A.T.S.A. ADM. PUBLICA (Bco)" },
  { value: 6216, label: "SUBOFICIALES.RET.PENITENCIARIA" },
  { value: 6221, label: "JOBSON INGENIERIA S.A. (Bco)" },
  { value: 6228, label: "CARRASCO S.A. (Bco)" },
  { value: 6100, label: "MUNIC. DE MONTERRICO (Bco)" },
  { value: 7004, label: "ZAPLA FORESTAL (Bco)" },
  { value: 6260, label: "CIRCULO RETIRADOS POLICIA PCIA" },
  { value: 6261, label: "A.P.O.P.S. (Bco)" },
  { value: 6000, label: "PARTICULARES (BCO)" },
  { value: 1102, label: "A.M.M.U.P." },
  { value: 22, label: "AMUCDEMS" },
  { value: 1501, label: "BANCO DE DESARROLLO DE JUJUY" },
  { value: 500, label: "CONVENIOS A RECUPERAR" },
  { value: 1103, label: "SERSIDER SAMICFIA" },
  { value: 6103, label: "SERSIDER (BANCO)" },
  { value: 2001, label: "SIN CARGO (COBRADORES/VENTAS)" },
  { value: 6001, label: "EMPLEADOS BCO MACRO S.A.(BCO)" },
  { value: 2500, label: "MUTUAL SAN VALENTIN" },
  { value: 3000, label: "ALTAS PROVISORIAS" },
  { value: 6500, label: "BANCO JUJUY (BCO)" },
  { value: 6501, label: "UTE-JAMA" },
  { value: 6504, label: "APPACE (BCO)" },
  { value: 6505, label: "ASOCIACION FIDES (Colegios)(B)" },
  { value: 6506, label: "ASOC. CIVIL LOS LAPACHOS (BCO)" },
  { value: 6507, label: "BALUT HNOS (BCO)" },
  { value: 6509, label: "CALIDAD DE VIDA S.R.L. (BCO)" },
  { value: 6510, label: "CARUSO (BCO)" },
  { value: 6512, label: "CLINICA LEDESMA" },
  { value: 6513, label: "CLUB GIMNASIA Y ESG. (BCO)" },
  { value: 6514, label: "COLEGIO FASTA" },
  { value: 6515, label: "COLEGIO N.SRA.DEL CARMEN (B)" },
  { value: 6516, label: "COLEGIO N.SRA.DEL HUERTO (B)" },
  { value: 6517, label: "COLEGIO SAGRADO CORAZON (BCO)" },
  { value: 6519, label: "COOP.TELEFONICA LA QUIACA (B)" },
  { value: 6520, label: "COOP.TELEF. L.G.SAN MARTIN (B)" },
  { value: 6521, label: "CENTRO EDUC. CRISTO REY (BCO)" },
  { value: 6522, label: "DEL NORTE S.A." },
  { value: 6523, label: "DELTA CONSTRUCCIONES (BCO)" },
  { value: 6524, label: "EDITOR S.A." },
  { value: 6525, label: "EMDEINS (Bco)" },
  { value: 6526, label: "EMPLEADOS DE E.J.E.S.A. (BCO)" },
  { value: 6527, label: "EMPLEADOS DE O.S.D.E. (BCO)" },
  { value: 6528, label: "EMPLEADOS DEL QUINTAR (BCO)" },
  { value: 6529, label: "EMPLEADOS DE SIMECOM (BCO)" },
  { value: 6530, label: "EMPRESA LEDESMA S.A." },
  { value: 6531, label: "EX-COMBATIENTES MALVINAS (BCO)" },
  { value: 6532, label: "FINCA SAN JOSE (BCO)" },
  { value: 6534, label: "INST.TEC. HERMINIO ARRIETA (B)" },
  { value: 6535, label: "INSTITUTO STA.TERESITA (BCO)" },
  { value: 6536, label: "MASSALIN PARTICULARES" },
  { value: 6537, label: "NTRA.SRA.MERCEDES -MONTERR-(B)" },
  { value: 6538, label: "PRESTADORES DE O.S.D.E (BCO)" },
  { value: 6541, label: "RADIO VISION JUJUY (BCO)" },
  { value: 6542, label: "SALVADOR MARINARO (BCO)" },
  { value: 6543, label: "SIN S.A. (BCO)" },
  { value: 6544, label: "SUPER TUNUYAN (BCO)" },
  { value: 6545, label: "TECHINT (BCO)" },
  { value: 6546, label: "TECNOVISION S.A. (BCO)" },
  { value: 6547, label: "TRANSPORTADROGAS DEL NORTE (B)" },
  { value: 6552, label: "SERV.SOCIALES FUTURO (BCO)" },
  { value: 6553, label: "S.A.E. (BCO)" },
  { value: 6554, label: "INST.DE INFORM.COMERCIALES (B)" },
  { value: 6555, label: "GESTION LABORAL (BCO)" },
  { value: 6556, label: "CLINICA DEL NIÑO (BCO)" },
  { value: 6558, label: "INSTITUTO DE RADIOLOGIA (BCO)" },
  { value: 6560, label: "ADMIN.CENTRAL PLANTA(GOB)(BCO)" },
  { value: 6561, label: "ADMIN.CENTRAL FUNC. (GOB)(BCO)" },
  { value: 6562, label: "CONSEJO EDUCACION CAPITAL (B)" },
  { value: 6563, label: "CONSEJO EDUCACION INTERIOR (B)" },
  { value: 6564, label: "DIGEMAS CAPITAL (BCO)" },
  { value: 6565, label: "DIGEMAS INTERIOR (BCO)" },
  { value: 6566, label: "M.B.SOCIAL (CAPITAL-PLANTA)(B)" },
  { value: 6567, label: "M.B.SOCIAL (CAPITAL-FUNCIO)(B)" },
  { value: 6568, label: "M.B.SOCIAL(INTERIOR-PLANTA)(B)" },
  { value: 6569, label: "M.B.SOCIAL(INTERIOR-FUNCIO)(B)" },
  { value: 6570, label: "VIALIDAD (BCO)" },
  { value: 6571, label: "MUNICIPALIDAD HUMAHUACA (BCO)" },
  { value: 6572, label: "MUNICIPALIDAD DE PALPALA (B)" },
  { value: 6573, label: "MUNICIP. SAN SALVADOR (BCO)" },
  { value: 6574, label: "MUNICIPALIDAD DE TILCARA (BCO)" },
  { value: 6575, label: "MUNICIP.DE L.G.SAN MARTIN (B)" },
  { value: 6576, label: "DIRECCION DE REC.HIDRICOS (B)" },
  { value: 6577, label: "INSTITUTO DE VIV.DE JUJUY (B)" },
  { value: 6578, label: "I.P.P.S. RESIDUAL (BCO)" },
  { value: 6579, label: "LEGISLATURA DE LA PCIA. (BCO)" },
  { value: 6580, label: "PODER JUDICIAL (BCO)" },
  { value: 6581, label: "SU.SE.PU. (BCO)" },
  { value: 6582, label: "TRIBUNAL DE CUENTAS (BCO)" },
  { value: 6600, label: "JUBILADOS - FRANJA 1 (BCO)" },
  { value: 6601, label: "JUBILADOS - FRANJA 2 (BCO)" },
  { value: 6602, label: "JUBILADOS - FRANJA 3 (BCO)" },
  { value: 6603, label: "JUBILADOS - FRANJA 4 (BCO)" },
  { value: 6604, label: "JUBILADOS - FRANJA 5 (BCO)" },
  { value: 6605, label: "JUBILADOS - FRANJA 6 (BCO)" },
  { value: 6606, label: "JUBILADOS - FRANJA 7 (BCO)" },
  { value: 6607, label: "JUBILADOS - FRANJA 8 (BCO)" },
  { value: 6608, label: "JUBILADOS - FRANJA 9 (BCO)" },
  { value: 6609, label: "JUBILADOS - FRANJA 10(BCO)" },
  { value: 6610, label: "JUBILADOS - FRANJA 11(BCO)" },
  { value: 6611, label: "JUBILADOS - FRANJA 12(BCO)" },
  { value: 6612, label: "JUBILADOS - FRANJA 13(BCO)" },
  { value: 6613, label: "JUBILADOS - FRANJA 14(BCO)" },
  { value: 6614, label: "JUBILADOS - FRANJA 15(BCO)" },
  { value: 9999, label: "DEBITOS - MACRO - SIN.N-CUENTA" },
  { value: 2005, label: "RIO GRANDE - TRANSITORIOS" },
  { value: 7500, label: "ACEROS ZAPLA - MACRO (Bco)" },
  { value: 6005, label: "FRONTERA S.A.  (Bco)" },
  { value: 6025, label: "POPULORUM PROGRESSIO (Bco)" },
  { value: 6006, label: "JUJUY PALACE HOTEL" },
  { value: 6450, label: "COOPERATIVA TEEL. PALPALA(Bco)" },
  { value: 3500, label: "PROVENCREED - T.CREDITO" },
  { value: 6615, label: "LIMSA S.A. (Bco)" },
  { value: 6616, label: "COLEGIO MEDICO (Bco)" },
  { value: 6617, label: "PORTADORES DE CRISTO (Bco)" },
  { value: 6618, label: "PROYECCION SACIFI" },
  { value: 6619, label: "EL CHAÑI S.R.L." },
  { value: 6620, label: "FRANCISCO MONTIEL S.A." },
  { value: 6621, label: "NEUMATICOS JUJUY S.A." },
  { value: 6622, label: "CREDIPLATA S.A." },
  { value: 6623, label: "JAMA S.A." },
  { value: 6624, label: "LIMPIEZA URBANA S.A." },
  { value: 6625, label: "FARMACIA INDEPENDENCIA" },
  { value: 6626, label: "TELECENTROS JUJUY S.A." },
  { value: 6627, label: "LA CASA DEL CICLISTA S.H." },
  { value: 6628, label: "SOCIEDAD DE TIRO, GIMN. Y ESG." },
  { value: 6629, label: "TECNO HIDRAULICA S.R.L." },
  { value: 6630, label: "COLEGIO DE ESCRIBANOS DE JUJUY" },
  { value: 6631, label: "MODAS DEL NORTE S.A." },
  { value: 6632, label: "FUNDACION O.CLA.DE." },
  { value: 6633, label: "PEDRO ANTONIO SEGURA LOPEZ" },
  { value: 6634, label: "COLEGIO DE FARMACEUTICOS" },
  { value: 8888, label: "CUENTAS PARA TRANFERENCIAS" },
  { value: 6073, label: "ALBERDI S.A. - BCO.MACRO" },
  { value: 6635, label: "JUBILADOS - FRANJA 16(BCO)" },
  { value: 6636, label: "JUBILADOS - FRANJA 17(BCO)" },
  { value: 6637, label: "JUBILADOS - FRANJA 18(BCO)" },
  { value: 6638, label: "JUBILADOS - FRANJA 19(BCO)" },
  { value: 6639, label: "JUBILADOS - FRANJA 20(BCO)" },
  { value: 6640, label: "P.A.E.B.A. - BCO.MACRO" },
  { value: 6666, label: "CAJA DE AHORROS DE SALTA" },
  { value: 6667, label: "CIRCULO DE ODONTOLOGOS" },
  { value: 1097, label: "COLEGIO JEAN PIAGET" },
  { value: 6641, label: 'MINERA "EL AGUILAR" MACRO(BCO)' },
  { value: 6642, label: "GUARDIAN S.R.L." },
  { value: 6643, label: "BIBLIOTECA POPULAR - GOB.(BCO)" },
  { value: 6668, label: "HIERROS LA QUIACA - (BCO)" },
  { value: 6669, label: "SINDICATURA LA ESPERANZA (B)" },
  { value: 6670, label: "UNIVERSIDAD JUJUY- MACRO" },
  { value: 6671, label: "COLEGIO DE ESCRIBANOS" },
  { value: 6672, label: "COOP.TEL.LIB.GRAL.SAN MARTIN" },
  { value: 7777, label: "DEBITOS - GESTION MOROSOS" },
  { value: 6673, label: "BANCO ACCION SOCIAL (BCO)" },
  { value: 6674, label: "FORESTAL NORTEÑA" },
  { value: 4000, label: "TARJETA VISA" },
  { value: 6675, label: "ANTIS - CONCESIONARIA (BCO)" },
  { value: 6676, label: "SANATORIO DEL ROSARIO" },
  { value: 6677, label: "BENITO ROGGIO SA. (BCO)" },
  { value: 6678, label: "RES. PSIC. SAN AGUSTIN (B)" },
  { value: 1270, label: "CONVENIO SUSPENDIDO !!!!!!!" },
  { value: 1265, label: "A.P.O.C." },
  { value: 6003, label: "EL URBANO S.R.L.(BANCO)" },
  { value: 6013, label: "PUSSETTO AUTOMOTORES S.A." },
  { value: 6644, label: "SUPERMERCADO NORTE" },
  { value: 6645, label: "HOTEL EL SILENCIO SA" },
  { value: 3600, label: "TARJETA CREDIMAS" },
  { value: 5010, label: "ADEP-ADMINISTRACION" },
  { value: 6040, label: "PORTICO CONSTRUCCIONES (B)" },
  { value: 6041, label: "CONS. PROF.DE CIENCIAS ECON." },
  { value: 6042, label: "STAR SERVICIOS - SEGURIDAD" },
  { value: 3800, label: "TARJETA NEVADA" },
  { value: 6583, label: "MUNICIPALIDAD PUESTO VIEJO" },
  { value: 6584, label: "SUPERMAT - JUJUY" },
  { value: 6585, label: "AUTOCIEL/AUTOSOL (CIEL SA)" },
  { value: 23, label: "FUNDACION 1º DE MAYO" },
  { value: 6586, label: "MUNICIPALIDAD DE EL CARMEN" },
  { value: 6679, label: "MINA PIRQUITAS (BCO)" },
  { value: 1266, label: "UNION BUS" },
  { value: 66, label: "ESTUDIANTES DE POLICIA" },
  { value: 1560, label: "EMPRENDIMIENTO RIO GRANDE" },
  { value: 6646, label: "EL OBRERO" },
  { value: 3900, label: "TARJETA SU-CREDITO" },
  { value: 6262, label: "S.O.E.M.E." },
  { value: 6680, label: "FORJA NORTE (BCO)" },
  { value: 3700, label: "TARJETA NARANJA" },
  { value: 3400, label: "TARJETA CREDICASH" },
  { value: 6587, label: "PAPEL NOA (BANCO)" },
  { value: 1570, label: "SIND.CHOF.REMIS/TRAN.ALT.S.P." },
  { value: 4100, label: "TARJETA MASTERCARD" },
  { value: 2006, label: "BOMBEROS VOLUNTARIOS STA CLARA" },
  { value: 6588, label: "SANATORIO LAVALLE (BCO)" },
  { value: 6589, label: "CARSA S.A (MUSIMUNDO)" },
  { value: 2010, label: "FRIGORIFICO PUNA" },
  { value: 6647, label: "COLEGIO DE KINESIOLOGOS(BCO)" },
  { value: 6681, label: "DIAVERUM - MEDICINA (BCO)" },
  { value: 6682, label: "MUNICIPALIDAD SAN ANTONIO" },
  { value: 6590, label: "MUNICIP. SAN ANTONIO (BCO)" },
  { value: 4200, label: "DEBITO BANCO RIO (OTROS BCOS)" },
  { value: 6683, label: "COMISION MUN.VOLCAN (BANCO)" },
  { value: 6684, label: "AUGUSTUS SRL (BANCO)" },
  { value: 6685, label: "DEMISA CONTRUCCIONES (BANCO)" },
  { value: 6686, label: "COOP.TABACALEROS PERICO (BCO)" },
  { value: 1099, label: "HIERRONORT SALTA S.R.L." },
  { value: 3888, label: "NEVADA - GESTION MOROSOS" },
  { value: 3666, label: "CREDIMAS - GESTION MOROSOS" },
  { value: 3777, label: "NARANJA - GESTION MOROSOS" },
  { value: 6687, label: "COLEGIO SANTA TERESITA (BCO)" },
  { value: 6688, label: "SALTA REFRESCOS (BCO)" },
  { value: 4004, label: "VISA - GESTION MOROSOS" },
  { value: 1001, label: "PARTIC - GESTION MOROSOS" },
  { value: 3999, label: "SU CREDITO - GESTION JUDICIAL" },
  { value: 666, label: "POLICIA - GESTION JUDICIAL" },
  { value: 6689, label: "CARREFOUR S.A." },
  { value: 8500, label: "GESTION MOROSOS - AFECTADOS" },
  { value: 3444, label: "CREDICASH - GESTION MOROSOS" },
  { value: 6690, label: "COMIS.MUNIC.SAN ANTONIO (BCO)" },
  { value: 6691, label: "COMIS.MUNICIPAL SUSQUES (BCO)" },
  { value: 6692, label: "DIR.PCIAL.DESARROLLO GAN(BCO)" },
  { value: 6693, label: "ASOCIACION TODOS JUNTOS (BCO)" },
  { value: 6694, label: "LOS TILIANES (PUCARA - BANCO)" },
  { value: 6695, label: "LLANOS S.R.L. (BCO)" },
  { value: 6696, label: "OCASA SA (BANCO MACRO)" },
  { value: 6697, label: "FINCA COMODIN (MACRO)" },
  { value: 6698, label: "EMPLEADOS APUAP (MACRO)" },
  { value: 6699, label: "BIBLIOTECA POPULAR (BANCO)" },
  { value: 6700, label: "LOS TILIANES ICFSA (BANCO)" },
  { value: 6701, label: "AUTOLUX S.A. (BANCO)" },
  { value: 6702, label: "COMISION MUNIC. YALA(BANCO)" },
  { value: 6703, label: "COLEGIO STA BARBARA (BCO)" },
  { value: 6704, label: "JUMI S.R.L. (BANCO)" },
  { value: 6705, label: "VEA - CENCOSUD (BCO)" },
  { value: 6706, label: "CENTRO CULT.TUPAC AMARU(PAEBA)" },
  { value: 6707, label: "SANTIAGO SAENZ SA (BANCO)" },
  { value: 6708, label: "EMPRESA SANTA ANA (BANCO)" },
  { value: 6709, label: "VIDEOTEL SRL" },
  { value: 6710, label: "CERVECERIA QUILMES MANZUR(BCO)" },
  { value: 6711, label: "CAPACITADORES GOBIERNO (BCO)" },
  { value: 25, label: "ADEP - DESC. PLANILLA" },
  { value: 26, label: "DISTRIBUIDORA SECCO SAN PEDRO" },
  { value: 6712, label: "CATTERING JUJUY SRL (BANCO)" },
  { value: 27, label: "HIERRONORT S.R.L." },
  { value: 6713, label: "EMPRESA SAN JORGE (BANCO)" },
  { value: 6714, label: "INGENIO RIO GRANDE (BANCO)" }
];

export const productores = [
  { value: 1, label: "OFICINA WERCHOW" },
  { value: 2, label: "OFICINA SAN PEDRO" },
  { value: 4, label: "OFICINA TESORERIA" },
  { value: 41, label: "LEON LUIS" },
  { value: 43, label: "RIVADENEIRA" },
  { value: 3, label: "OFICINA PALPALA" },
  { value: 8, label: "GARECA PEDRO" },
  { value: 14, label: "TRUJILLO" },
  { value: 80, label: "LUQUE EUFROCINA" },
  { value: 69, label: "HUMACATA ELVIO" },
  { value: 5, label: "OFICINA PERICO" },
  { value: 138, label: "GOMEZ CLELIA" },
  { value: 413, label: "MARIA EUGENIA RUEDA" },
  { value: 435, label: "VIRGINIA RUEDA ARMOA" },
  { value: 903, label: "MESSORI DOMINGO" },
  { value: 440, label: "ALBERTO GAZQUEZ" },
  { value: 908, label: "MARCELO QUIROZ" },
  { value: 21, label: "GAZQUEZ MARIANA" },
  { value: 444, label: "DIAZ ADOLFO" },
  { value: 7, label: "OFICINA - LEDESMA" },
  { value: 459, label: "NELSON CRUZ" },
  { value: 806, label: "CACERES, PATRICIA (CSJ)" },
  { value: 460, label: "CENTRO MEDICO INTEGRAL" },
  { value: 461, label: "EFRAIN GONZALEZ  (SRL)" },
  { value: 915, label: "RAUL URBINA" },
  { value: 917, label: "GUILLERMO SORAIRE" },
  { value: 918, label: "MARIANO CHAGARAY" },
  { value: 920, label: "MORENO EVANGELINA" },
  { value: 921, label: "FABIAN ROSSETTI" },
  { value: 809, label: "RITA VALDIVIEZO   (CSJ)" },
  { value: 807, label: "LORENA ELISA CARI (CSJ)" },
  { value: 808, label: "GAYARDO, VIRGINIA (CSJ)" },
  { value: 801, label: "DESMEDT, MARIA DEL MILAG (CSJ)" },
  { value: 802, label: "CHOCOBAR, JAVIER M (CSJ)" },
  { value: 803, label: "LIQUITAY, ALEJANDRO F  (CSJ)" },
  { value: 924, label: "SILVIA JUAREZ" },
  { value: 813, label: "MARIA ISABEL PEREIRA  (CSJ)" },
  { value: 814, label: "ANALIA VERONICA VALDEZ  (CSJ)" },
  { value: 815, label: "ALEJANDRA BELTRAN" },
  { value: 816, label: "GERARDO DE MENDOZA" },
  { value: 929, label: "BANDUR PABLO" },
  { value: 50, label: "FARFAN JOSE ANTONIO" },
  { value: 55, label: "MARIANA GASQUEZ" },
  { value: 820, label: "SEBASTIAN PEREZ" },
  { value: 821, label: "ROBERTO FIGUEROA" },
  { value: 822, label: "PABLO EZEQUIEL DURAN" },
  { value: 930, label: "DANIEL PEREZ" },
  { value: 931, label: "NESTOR GABRIEL PEREZ" },
  { value: 932, label: "ORTEGA, IVONE" },
  { value: 933, label: "SEBASTIAN HAITIT" },
  { value: 935, label: "CECILIA VILCA" },
  { value: 936, label: "DAVID RODRIGO LOPEZ" },
  { value: 937, label: "RODRIGO JAVIER ARROYO ROJAS" },
  { value: 939, label: "MATIAS JOSE BARRIONUEVO" },
  { value: 940, label: "MIGUEL ALEJANDRO VILTE" },
  { value: 941, label: "LUIS ALBERTO RODRIGUEZ" },
  { value: 942, label: "HECTOR SANTOS QUIROZ" },
  { value: 944, label: "SILVANA NATALIA ESTRADA" },
  { value: 945, label: "PABLO SALAS" },
  { value: 946, label: "MARIA EMILIA CARABAJAL" },
  { value: 947, label: "SILVANA NATALIA ESTRADA" },
  { value: 948, label: "SEBASTIAN FERNANDEZ" },
  { value: 950, label: "MUTUAL SAN JOSE (GABRIEL)" },
  { value: 951, label: "GISELA MAMANI" },
  { value: 952, label: "MAXIMILIANO S. MORCILLO" },
  { value: 953, label: "GISELA ROMERO" },
  { value: 954, label: "MATIAS NAVARRO" },
  { value: 955, label: "PRISCILA BRZEZINSKI" },
  { value: 956, label: "HUGO BARBOSA" },
  { value: 957, label: "ROMINA UBAGO" },
  { value: 958, label: "JORGE  RIOS" },
  { value: 959, label: "MARIANA NANCI ABENDAÑO" },
  { value: 960, label: "MARINA   VEGA" },
  { value: 961, label: "MARIA TOLABA" },
  { value: 962, label: "SILVANA QUIROGA" },
  { value: 963, label: "VALERIA SANCHEZ" },
  { value: 964, label: "MARCELA VALDEZ" },
  { value: 965, label: "IVAN MAMANI" },
  { value: 966, label: "ROSENDO VENTURA VALDEZ" },
  { value: 901, label: "FARFAN (PERICO)" },
  { value: 967, label: "ROMAN MARTIN ARANZULA" },
  { value: 968, label: "ABEL GARECA" },
  { value: 969, label: "SANDRA LOPEZ CAZON" },
  { value: 970, label: "BENITES IVAN" },
  { value: 868, label: "MEDINA LUIS" },
  { value: 973, label: "GIMENA CRUZ MURILLO" },
  { value: 974, label: "RODRIGUEZ GISELLA" },
  { value: 975, label: "NELSON CASIMIRO" },
  { value: 977, label: "SIVILA VERONICA" },
  { value: 978, label: "HUANCA LUCIA" },
  { value: 979, label: "CASASOLA RITA DEL VALLE" },
  { value: 981, label: "PABLO ARNALDO ARANA" },
  { value: 984, label: "AÑASGO VICTOR HUGO" },
  { value: 985, label: "BORNEMAN ROBERTO" },
  { value: 995, label: "MAMANI MICAELA" },
  { value: 996, label: "PATRICIA IVONE TORONCONTE" },
  { value: 997, label: "EMANUEL GALIQIO" },
  { value: 998, label: "EUGENIO MARCELO VALENTE" },
  { value: 980, label: "SILVIA BALDERRAMA" },
  { value: 983, label: "LEAL GABRIELA" },
  { value: 982, label: "IBARRA MARIA DEBORA" },
  { value: 999, label: "VALDA CARLOS" },
  { value: 972, label: "TOLAY GISELA" },
  { value: 971, label: "TASTACA RUBEN" },
  { value: 949, label: "NADIA MELISA SANTIS" },
  { value: 938, label: "TANIA ALEJANDRA CAZON" },
  { value: 986, label: "OROZCO ANDRA SOLEDAD" },
  { value: 987, label: "MANUEL EMILIO CASTAÑEDA" },
  { value: 988, label: "RODRIGUEZ MARCELO GUSTAVO" },
  { value: 990, label: "PALOMINO LUCIA" },
  { value: 976, label: "ROJAS SUSANA BEATRIZ" },
  { value: 943, label: "EMILIO MACHACA" },
  { value: 927, label: "CRISTIAN ORLANDO ORTEGA" },
  { value: 989, label: "CHAVEZ ESTEBAN W." },
  { value: 500, label: "EDUARDO BALBIN" },
  { value: 501, label: "CARBALLO JULIO" },
  { value: 502, label: "AVILES SABRINA" },
  { value: 503, label: "AVILEZ LUIS" },
  { value: 504, label: "VENEGAS MARIA" },
  { value: 505, label: "DUARTE EFRAIN" },
  { value: 506, label: "HYON JUAN PABLO" },
  { value: 507, label: "CASTAÑEDA MANUEL EMILI" },
  { value: 508, label: "RAMIREZ MICAELA INES" },
  { value: 509, label: "DIEGO RUBEN CADENAS" },
  { value: 510, label: "GUIDO EMILIO CADENAS" },
  { value: 511, label: "VICTORIA CASTILLO" },
  { value: 512, label: "MARTA ISABEL ALEJO" },
  { value: 513, label: "MATIAS JUAN GARCIA" },
  { value: 516, label: "URO JORGE" },
  { value: 517, label: "CONDORI ALEJANDRA" },
  { value: 518, label: "ARENAS ANTOÑETA" },
  { value: 519, label: "CONDORI RAMONA" },
  { value: 515, label: "ESPINOSA LAURA" },
  { value: 520, label: "LUJAN GONZALEZ" },
  { value: 521, label: "RAMIREZ MICAELA" },
  { value: 522, label: "ABIGAIL FERNANDEZ" },
  { value: 523, label: "SAUGG RAQUEL" },
  { value: 524, label: "QUIPILDOR MARIA" },
  { value: 900, label: "MORALES JUAN CARLOS" },
  { value: 525, label: "SEBASTIAN ARMATA" },
  { value: 526, label: "MENDOZA CRISTIAN" },
  { value: 527, label: "MENDOZA ENRIQUE" },
  { value: 528, label: "CLAURE ARIEL" },
  { value: 529, label: "ESPINDOLA HECTOR MARIANO" },
  { value: 530, label: "MARIA EUGENIA MORENO" },
  { value: 531, label: "ALBORNOZ CESAR DANIEL" },
  { value: 532, label: "VEGA DANIEL GONZALO" },
  { value: 533, label: "LOPEZ ARMATA SEBASTIAN" },
  { value: 534, label: "EDUARDO OSAN" },
  { value: 535, label: "ROMAN IGNACIO G" },
  { value: 536, label: "MONTOYA FERNANDO MARTIN" },
  { value: 537, label: "MEDINA CRISTIAN" },
  { value: 538, label: "ALFARO CESAR" },
  { value: 539, label: "BASPINEIRO ROLANDO" },
  { value: 542, label: "SORUCO JOSE" },
  { value: 541, label: "RICARDO RIVERO" },
  { value: 543, label: "LEON ALAN" },
  { value: 545, label: "CACERES JOAQUIN" },
  { value: 544, label: "MARIELA TORRES" },
  { value: 546, label: "JUDITH I. A. CABANA ORTIZ" },
  { value: 547, label: "FARFAN RICARDO" },
  { value: 540, label: "TAGLIOLI, ROMAN" },
  { value: 548, label: "HUGO JAVIER GARCIA" },
  { value: 549, label: "CUNCHILA MAIRA" },
  { value: 551, label: "YAMILA IVONE VALDEZ" },
  { value: 552, label: "ESPINDOLA HECTOR" },
  { value: 553, label: "REBECA OROZCO" },
  { value: 554, label: "SARDINA JIMENA" },
  { value: 555, label: "ALARCON VALERIA" },
  { value: 556, label: "ALFARO GUSTAVO" },
  { value: 912, label: "BANDUR PABLO" },
  { value: 557, label: "CAZON JUAN FACUNDO" },
  { value: 558, label: "SANCHEZ PEDRO JOSE F." },
  { value: 559, label: "ROLLE RICARDO SEBASTIAN" },
  { value: 550, label: "SOZA MARTIN MIGUEL" },
  { value: 560, label: "ESCOBAR GONZALEZ, LOURDES NOEL" },
  { value: 561, label: "DAVALOS LAURA ELIZABETH" },
  { value: 562, label: "FIGUEROA GLENDA ELISA VALERIA" },
  { value: 563, label: "LARA CECILIA RAFAELA" },
  { value: 564, label: "LEON FERNANDA PAOLA" },
  { value: 565, label: "SANCHEZ MARIANA" },
  { value: 566, label: "DIAZ LUCIANO RODOLFO WALTER" },
  { value: 567, label: "MARIANA CECILIA COLOMBO" },
  { value: 568, label: "MELISA GABRIELA PERALTA" },
  { value: 569, label: "FERREYA ZULMA GRACIELA" },
  { value: 570, label: "PACHECO MERCEDES DE LOS ANGELE" },
  { value: 571, label: "ROJAS CLAUDIA DANIELA" },
  { value: 572, label: "BERTOLINI SILVANA MERCEDEZ" },
  { value: 573, label: "LIDIA RITA CORREA" },
  { value: 574, label: "TOLEDO ANALIA CECILIA" },
  { value: 575, label: "BERNAL NADIA DE LOS ANGELES" },
  { value: 576, label: "ALDERETE YESICA ANABEL" },
  { value: 577, label: "LAURA CINTIA FABIANA" },
  { value: 578, label: "NYMAN GISELLA PATRICIA" },
  { value: 579, label: "CONDE CATRIEL" },
  { value: 580, label: "AROZARENA CRISTIAN BABIL" },
  { value: 581, label: "ALDERETE YESICA ANABEL" },
  { value: 582, label: "PORCEL FERNANDA" },
  { value: 583, label: "VALERO JULIANA CLARA" },
  { value: 584, label: "BASOALTO ADRIANA VERONICA" },
  { value: 585, label: "VERGARA JUAN CARLOS" },
  { value: 586, label: "BALDERRAMA LAURA VERONICA" },
  { value: 587, label: "MARAS YESICA MARILINA" },
  { value: 588, label: "URO JORGE NAHUEL CATRIEL" },
  { value: 589, label: "MARTINEZ MARIELA ALEJANDRA" },
  { value: 590, label: "CRUZ GLADYS M." },
  { value: 591, label: "MATIAS LISANDRO JAVIER" },
  { value: 592, label: "CASTILLO SILVANA E" },
  { value: 593, label: "MOLINA ROMINA S." },
  { value: 594, label: "MIRANDA ESTER FLORENCIA" },
  { value: 595, label: "MANSILLA GISELA VIVIANA" },
  { value: 596, label: "MILLAN DANIELA LILIANA" },
  { value: 597, label: "COULTHARD ANDREA ELIZABTH" },
  { value: 598, label: "ANACHURI ALIZABETH VANESA" },
  { value: 599, label: "PILAR FERNANDO MARTIN" },
  { value: 600, label: "CASAS DAVID FRANCISCO" },
  { value: 601, label: "SAAVEDRA JUAN JOSE EMANUEL" },
  { value: 602, label: "MAMANI ISMAEL CARLOS DAVID" },
  { value: 603, label: "MOLLERACH SERGIO DANIEL" },
  { value: 604, label: "GRAMAJO CAMILA" },
  { value: 605, label: "VELAZQUEZ CARLOS ALBERTO" },
  { value: 606, label: "ABREGU GABRIEL ANTONIO" },
  { value: 607, label: "DOLSAN DAVID HECTOR" },
  { value: 608, label: "VACAFLOR ISABEL" },
  { value: 609, label: "VELAZQUEZ SERGIIO SEBASTIAN R" },
  { value: 610, label: "MARINO DIEGO RICARDO" },
  { value: 611, label: "PEREYRA IRIS SAMANTA" },
  { value: 612, label: "MORALES GASTON ARIEL" },
  { value: 613, label: "GARNICA RUTH ANAHI CELESTE" },
  { value: 614, label: "MENDOZA EMILIO RICARDO" },
  { value: 615, label: "SIDONI MELINA" },
  { value: 616, label: "PAREDES JUAN MANUEL" },
  { value: 617, label: "PONCE VALERIA VANESA" },
  { value: 618, label: "FOSSATTI ELIANA ANTONELLA" },
  { value: 619, label: "BASOALTO BRENDA MARIANA" },
  { value: 620, label: "GUZMAN FLORENCIA ITATI" },
  { value: 621, label: "MOLINA PAOLA LILEN" },
  { value: 622, label: "CAMPILLAY DIEGO GERARDO" },
  { value: 623, label: "HERRERA RAUL SANTIAGO" },
  { value: 624, label: "HYON ANALIA JIMENA" },
  { value: 625, label: "GARCIA ATILIO" },
  { value: 626, label: "IBAÑEZ SOLEDAD" },
  { value: 627, label: "SOTELO ANAHI" },
  { value: 628, label: "TOLAVA ANGEL PABLO" },
  { value: 629, label: "CHILO MARINA GRACIELA" },
  { value: 630, label: "CAYO MARTINEZ, MARIA BELEN" },
  { value: 631, label: "QUINTANA MARIA NATALIA" },
  { value: 632, label: "SARAPURA NANCY FERNANDA" },
  { value: 633, label: "ALVAREZ JAVIER" },
  { value: 634, label: "ROLON MARINA" },
  { value: 635, label: "ZUBIETA MAYRA" },
  { value: 636, label: "CASAS LAURA VERONICA" },
  { value: 637, label: "CADENA MIRIAN VANESA" },
  { value: 638, label: "GUARNIERI JESUS SEBASTIAN" },
  { value: 639, label: "GASPAR NATALIA MELANI" },
  { value: 640, label: "SMITH JOSEFINA ANTONELA" },
  { value: 641, label: "PONCE CAMILA" },
  { value: 642, label: "CORONEL SEBASTIAN MATIAS" },
  { value: 643, label: "CORONEL ORTIZ, SEBASTIAN MATIA" },
  { value: 644, label: "CORONEL SEBASTIA MATIAS" },
  { value: 645, label: "HUAILLA JOSE FERNANDO" },
  { value: 646, label: "DREER MARTIN" },
  { value: 647, label: "CASTRO ADRIANA" },
  { value: 648, label: "CRUZ NOEMI" },
  { value: 649, label: "CASTILLO NAHUEL URIEL" },
  { value: 650, label: "CASTILLO DANIELA MARISEL" },
  { value: 651, label: "PELOSO ANALIA" },
  { value: 652, label: "CORTEZ DARIO ORLANDO" },
  { value: 653, label: "HERRERA DANIEL MARCELO" },
  { value: 654, label: "SMITER JOSE" },
  { value: 655, label: "ARAMAYO SEBASTIAN TOMAS" },
  { value: 656, label: "DREER MARTIN" },
  { value: 657, label: "MORENO MARIO EZEQUIEL" },
  { value: 658, label: "MARQUEZ LUIS ALFREDO" },
  { value: 659, label: "CRUZ NICOLE ESTEFANI" },
  { value: 660, label: "VIDE LORENA MARIA SOLEDAD" },
  { value: 661, label: "TEJERINA FLORENCIA ABIGAIL" },
  { value: 662, label: "VELASQUEZ VERONICA GABRIELA" },
  { value: 663, label: "LEITHOLD ESTELA GUILLERMINA" },
  { value: 664, label: "RAMOS ABIGAIL CRISTINA DEL CAR" },
  { value: 665, label: "PATAGUA BELEN DE LOS ANGELES" },
  { value: 666, label: "MARTINEZ VICTOR FABIAN" },
  { value: 667, label: "AYBAR PAOLA AYELEN" },
  { value: 668, label: "COLQUE PABLO LUIS" },
  { value: 669, label: "ROJAS ROMINA" },
  { value: 670, label: "CRUZ VERONICA" },
  { value: 671, label: "MAIZAREZ MICAELA FERNANDA" },
  { value: 672, label: "LOPEZ CHAILE CARLA ROMINA" },
  { value: 673, label: "MIRANDA LUIS JAVIER" },
  { value: 674, label: "LOPEZ ARACELI DEL VALLE" },
  { value: 675, label: "CONTRERAS JANINA VALERIA" },
  { value: 676, label: "AMABLE EDUARDO ISMAEL" },
  { value: 677, label: "LOPEZ TATIANA" },
  { value: 678, label: "GARCIA RAUL VICTOR" },
  { value: 679, label: "CORTEZ FABIANA" },
  { value: 680, label: "MOREJON ANDREA" },
  { value: 681, label: "CORTEZ JUAN" },
  { value: 682, label: "SINGH JUAN PABLO" },
  { value: 683, label: "BRONEE FRANCO MAXIMILIANO" },
  { value: 684, label: "SEGOVIA CARLA MARISEL" },
  { value: 685, label: "RAMIREZ GLADIS BEATRIZ" },
  { value: 686, label: "CUELLAR BRUNO HERNAN" },
  { value: 687, label: "NICOLAS ERICA SELENA" },
  { value: 688, label: "VILLATARCO NICOLAS AUGUSTO" },
  { value: 689, label: "DELGADO CINTIA VALERIA" },
  { value: 690, label: "DIAZ DANA FLORA DEL VALLE" },
  { value: 691, label: "CORONEL ORTIZ,EXEQUIEL MAXIMIL" },
  { value: 692, label: "CEBALLOS ABDALA" },
  { value: 693, label: "SALINAS ALFONSO JESUS" },
  { value: 694, label: "ORTEGA DANTE FABIAN EDUARDO" },
  { value: 695, label: "ALI NAHIR JOZABEL" },
  { value: 696, label: "NAVARRO IGNACION DAVID" },
  { value: 697, label: "MARAÑON LUCIANA ALICIA" },
  { value: 698, label: "MURILLO ARAMAYO,DANIEL OSVALDO" },
  { value: 699, label: "URTADO LOPEZ,MACARENA KAREN" },
  { value: 700, label: "ROSALES, JONATHAN ISMAEL" },
  { value: 701, label: "VEGA, MARCELO GABRIEL" },
  { value: 249, label: "ALVAREZ KARINA MARY" },
  { value: 702, label: "URO MARCELO LINQUE" },
  { value: 703, label: "NAVARRO MASSARI, NICOLAS MARCO" },
  { value: 704, label: "QUISPE GISELA ANAHI" },
  { value: 144, label: "MARIA ALEJANDRA VAEZ" },
  { value: 705, label: "QUIROGA GISELA DEL VALLE" },
  { value: 706, label: "ALARCON MIRIAN" },
  { value: 707, label: "JALIL FABIANA" },
  { value: 708, label: "MARTINEZ MAXIMILIANO JUAN JOSE" },
  { value: 709, label: "GONZALEZ MARCELA TERESA" },
  { value: 710, label: "ZUAREZ RODRIGO FERNANDO" },
  { value: 711, label: "YAMPA LOUDES DANIELA" },
  { value: 712, label: "ROLON JIMENA RAQUEZ NOELIA" },
  { value: 713, label: "ZAMBRANO VANESA RAQUEL" },
  { value: 714, label: "ROBLES CAROLINA MARLENE" },
  { value: 715, label: "SALINAS MARIA ELISA" },
  { value: 716, label: "ZARZA TERESITA DEL CARMEN" },
  { value: 717, label: "GUZMAN XIMENA" },
  { value: 718, label: "BURGOS BRENDA" },
  { value: 719, label: "FLORES IVANA NOELIA" },
  { value: 720, label: "REYNOSO VANINA" },
  { value: 721, label: "MORALES LEONARDO GUSTAVO" },
  { value: 722, label: "CORREA DANIEL HERNAN" },
  { value: 723, label: "VERA FEDERICO EZEQUIEL" },
  { value: 724, label: "YAMPA DAIANA DEL ROSARIO" },
  { value: 725, label: "PLAZA ROXANA MARIA FLORENCIA" },
  { value: 726, label: "RAMOS JESUS SALVADOR" },
  { value: 727, label: "REY VAZQUEZ JAVIER ALEJANDRO" },
  { value: 728, label: "VELAZQUEZ LUCIANA JIMENA" },
  { value: 729, label: "CASTILLO CARINA FABIOLA" },
  { value: 730, label: "PEDRAZA VERONICA INES YOLANDA" },
  { value: 731, label: "PEREZ LORENA PAOLA" },
  { value: 732, label: "MURUA JOEL ANDRES" },
  { value: 733, label: "ROCHA JOSE ANTONIO" },
  { value: 734, label: "ALEMAN JUAN" },
  { value: 735, label: "SILVESTRE MARIA MAGDALENA" },
  { value: 736, label: "MACHICADO MARIANA DE LOS ANGEL" },
  { value: 737, label: "MONICA ROSALIA CASTILLO" },
  { value: 738, label: "MARTINEZ MARIA ISABEL" },
  { value: 739, label: "ALDANA FEDERICO" },
  { value: 740, label: "CENTELLAS NOELIA ALEJANDRA" },
  { value: 741, label: "TEJERINA ALEJANDRO" },
  { value: 742, label: "LOPEZ LUCIANO" },
  { value: 812, label: "AGOSTINIA ROCIO VILLARREAL" },
  { value: 823, label: "MONICA PUZZI" },
  { value: 824, label: "MONICA NOEMI CACHIZUMBA" },
  { value: 825, label: "DIEGO GASTON CORAITA" },
  { value: 826, label: "FABIOLA YABICHINO" },
  { value: 827, label: "CECILIA ROMERO" },
  { value: 828, label: "YESICA NOEL FEDERICO" },
  { value: 829, label: "JONATAN ANGELO" },
  { value: 830, label: "NORMA CONDORI" },
  { value: 831, label: "NORMA BEATRIZ ZAMPINO" },
  { value: 832, label: "ANDREA CELESTE PEDRONI" },
  { value: 833, label: "ADRIANA CEJAS" },
  { value: 834, label: "MARIA FLORENCIA AGUIRRE" },
  { value: 835, label: "ANA PAULA DEL HUERTO DIAZ" },
  { value: 836, label: "BRUNO NICOLAS BENITEZ" },
  { value: 837, label: "MARIANA ISABEL ORTIZ" },
  { value: 839, label: "SAUL DEPRETIS" },
  { value: 838, label: "FAVIO ALEXIS FERNANDEZ" },
  { value: 840, label: "MARCELO ALEJANDRO GONZALEZ" },
  { value: 841, label: "GONZALOS ABALOS" },
  { value: 842, label: "MONICA NOEMI CACHIZUMBA" },
  { value: 843, label: "YESICA IVONE AGUILERA" },
  { value: 844, label: "VERONICA MAGALI BELEN" },
  { value: 845, label: "AGOSTINA PENALBA" },
  { value: 846, label: "BELEN GUADALUPE TAPIA" },
  { value: 847, label: "ELIANA MARIA GABRIELA OCHOA" },
  { value: 848, label: "AMAYA FEDERICO EZEQUIEL" },
  { value: 10, label: "CRUZ ANTONIO" },
  { value: 11, label: "SORIA ANTONELLA" },
  { value: 849, label: "ARIEL TOLEDO" },
  { value: 850, label: "ANDREA ELIDE DIAZ" },
  { value: 851, label: "MARISA F. CARRIZO" },
  { value: 852, label: "MARCELO MARTIN GONZALES" },
  { value: 854, label: "LUIS FRANCISCO BELTRAN" },
  { value: 855, label: "CARLOS ALEJANDRO HERRERA" },
  { value: 856, label: "LUANA LOPEZ MENDEZ" },
  { value: 857, label: "MARCOS RODRIGUEZ" },
  { value: 858, label: "EMILIO SALITON" },
  { value: 859, label: "NICOLAS GABRIEL MANSUR" },
  { value: 860, label: "MAURO GONZALEZ" },
  { value: 861, label: "ALEJANDRA TEJERINA" },
  { value: 867, label: "NOELIA ALEJANDRA MAIGUA" },
  { value: 862, label: "MELIZA DEL VALLE ROCHA" },
  { value: 863, label: "INGRID AYELEN POLLI" },
  { value: 864, label: "JUAN ISMAEL SADIR" },
  { value: 865, label: "ANGELA BEATRIZ CHIJO" },
  { value: 873, label: "ERSILIA MAGDALENA VASQUEZ" },
  { value: 874, label: "GABRIELA ROCIO ACOSTA" },
  { value: 875, label: "MARLENE DEL VALLE VILTE" },
  { value: 876, label: "ROSA SILVIA SAJAMA" },
  { value: 872, label: "GISELA ABIGAIL MAMANI" },
  { value: 877, label: "MARA CRISTINA MAMANI" },
  { value: 878, label: "SONIA RAQUEL ARROYO" },
  { value: 879, label: "RAUL ANIBAL SOLIS" },
  { value: 747, label: "JORGELINA ZERPA" },
  { value: 748, label: "AUGUSTO ALCOCER" },
  { value: 749, label: "YESICA VELASQUEZ" },
  { value: 750, label: "SOFIA GUTIERREZ" },
  { value: 751, label: "MARIANA DE LOS A. BELMONTE" },
  { value: 752, label: "NICOLAS VILLATARCO" },
  { value: 745, label: "JUAN PABLO QUIROGA" },
  { value: 756, label: "CLARA ABIGAIL JARAMILLO" },
  { value: 866, label: "ANTONELLA VANIVA SANCHEZ" },
  { value: 760, label: "CRISTIAN ARIEL TEJERINA" },
  { value: 880, label: "MARCOS CEREZO" },
  { value: 881, label: "LEANDRO TORREZ" },
  { value: 882, label: "MATIAS GUANTAY" },
  { value: 883, label: "JACOBO RODRIGUEZ" },
  { value: 884, label: "AYLEN MOGRO" },
  { value: 885, label: "CRISTIAN MARRERO" },
  { value: 886, label: "NANCY FARFAN" },
  { value: 890, label: "PATRICIA SOLEDAD JEREZ" },
  { value: 891, label: "CRISTIAN MARAS" },
  { value: 892, label: "PAULA FLORENCIA MAMANI" },
  { value: 871, label: "MARIA DEL HUERTO GALIAN" },
  { value: 889, label: "SONIA ELIZABETH LOPEZ" },
  { value: 895, label: "MARIANO SANCHEZ" },
  { value: 893, label: "NEHUEN AVILA" },
  { value: 896, label: "CONSTANZA AGUSTINA VALDEZ" },
  { value: 897, label: "JUAN PABLO IBANES" },
  { value: 991, label: "ARNALDO FABIAN SEGOVIA" },
  { value: 757, label: "NOELIA BELEN ARROYO" },
  { value: 758, label: "MONICA KARINA SOTO" },
  { value: 759, label: "VANESA GOROSITO" },
  { value: 761, label: "JULIO EMANUEL JURADO" },
  { value: 762, label: "JOSE OMAR GUTIERREZ" },
  { value: 763, label: "NANCY LLALLE" },
  { value: 780, label: "MARIA VICTORIA BERNACHER" },
  { value: 781, label: "SILVANA BERTOLIN" },
  { value: 782, label: "PAOLA LORENA BARRIOS" },
  { value: 783, label: "GUSTAVO ROMERO" },
  { value: 784, label: "CORINA GIMENEZ" },
  { value: 774, label: "ANTONIA IVANA SILVESTRE" },
  { value: 775, label: "IRMA ANABEL COCA" },
  { value: 776, label: "ESTELA MONICA TARIFA" },
  { value: 777, label: "JAIRO ERNESTO TORRES" },
  { value: 785, label: "IGNACIO AGUSTIN TORRES" },
  { value: 764, label: "DANIELA ALEJANDRA CASTANO" },
  { value: 765, label: "CLAUDIA CAROLINA CABRERA" },
  { value: 894, label: "MARIANA BEATRIZ TOBI" },
  { value: 743, label: "GEREZ DANIELA ALEJANDRA" },
  { value: 744, label: "GUTIERREZ ERICA CECILIA" },
  { value: 766, label: "GUTIERREZ MARIANA" },
  { value: 767, label: "BELTRAN SANDRA CRISTINA" },
  { value: 887, label: "SANDRA APAZA" },
  { value: 790, label: "ANDRES LAUREANO" },
  { value: 791, label: "JUAN MIGUEL PELOC" },
  { value: 786, label: "MARIA ANGELICA ROJAS" },
  { value: 787, label: "CRISTIAN JAVIER MONTERO" },
  { value: 788, label: "JORGE EDUARDO MONTERO" },
  { value: 789, label: "AUGUSTO MAXIMILIANO CASTRO" },
  { value: 778, label: "NICOLAS JESUS MARANON" },
  { value: 779, label: "FRANCISCO F. CHAMORRO FIGUEROA" },
  { value: 773, label: "ELIANA GONZALEZ" },
  { value: 792, label: "RAMON MAURICIO CRUZ" },
  { value: 793, label: "RODRIGO ALEJANDRO MELANO" },
  { value: 301, label: "JULIETA YANINA BARBOZA" },
  { value: 302, label: "CAROLINA GALIANO" },
  { value: 303, label: "ELBIO GUSTAVO JARAMILLO ROBLES" },
  { value: 304, label: "RICARDO MAXIMILIANA TAPIA" },
  { value: 305, label: "NATALIA VALERIA MAIDANA" },
  { value: 306, label: "CRISTIAN MATIAS ARGANARAZ" },
  { value: 869, label: "GABRIELA CHAUQUE" },
  { value: 307, label: "GABRIEL MARIANO TORANZO" },
  { value: 308, label: "MARIA CELESTE SALINAS" },
  { value: 309, label: "GISELA MIRIAN TOLAY" },
  { value: 310, label: "FIORELA FLORENCIA G. OCHOA" },
  { value: 311, label: "YAMILA SOLEDAD MARTIN" },
  { value: 312, label: "EMANUEL EXEQUIEL ZARATE" },
  { value: 313, label: "NATALIA CAROLINA CARRIZO" },
  { value: 314, label: "MELINA ANABEL JURADO" },
  { value: 315, label: "ROXANA GISELA VILCA" },
  { value: 316, label: "VIVIANA MARIA J. LIZONDO" },
  { value: 317, label: "IVAN ALBERTO MENDEZ" },
  { value: 318, label: "MARIA ISABEL GARCIA" },
  { value: 320, label: "CARLA MARIANELA MORALES" },
  { value: 321, label: "PABLO DAVID IZETTA" },
  { value: 322, label: "DIEGO SEBASTIAN HUERTAS" },
  { value: 323, label: "ANDREA PAOLA ARMEYA" },
  { value: 324, label: "VLADIMIR ALVARO VILLARRUBIA" },
  { value: 325, label: "CARLA LEILA ALCOCER" },
  { value: 326, label: "BRENDA MACHACA CARABALLO" },
  { value: 327, label: "ESTRELLA NOELIA PUCA" },
  { value: 328, label: "SUSANA ELIZABETH MAMANI" },
  { value: 329, label: "CLAUDIA SILVINA FLORES" },
  { value: 330, label: "MATIAS JAVIER OLMOS" },
  { value: 331, label: "LAURA ANAHI SAJAMA" },
  { value: 332, label: "ANGEL GUSTAVO ARIEL" },
  { value: 794, label: "MERCADO MELISA ROXANA" },
  { value: 795, label: "PANIQUE BRENDA CECILA" },
  { value: 796, label: "BAZAN ANGELA MARIA DEL ROSARIO" },
  { value: 797, label: "CARDOZO NATASHA BELEN" },
  { value: 798, label: "MARTINEZ ROBERTO CRISTIAN" },
  { value: 799, label: "RODRIGUEZ PAULA FLORENCIA" }
];

export const planes = [
  { value: "S", label: "SOLO SEPELIO" },
  { value: "B", label: 'SALUD "B"' },
  { value: "D", label: "DORADO" },
  { value: "A", label: 'SALUD "A"' },
  { value: "C", label: "SEPELIO-VIEJO" },
  { value: "N", label: "PLAN (N)-VIEJO" },
  { value: "F", label: "FAMILIAR" },
  { value: "W", label: "B-BIS" },
  { value: "V", label: "SEGURO DE VIDA" },
  { value: "E", label: "PLAN S100" },
  { value: "M", label: "POR MODULOS" },
  { value: "P", label: "NOVELL-PREPAGO" },
  { value: "M", label: "FAMILIAR A" },
  { value: "M", label: "FAMILIAR B" },
  { value: "M", label: "FAMILIAR C" },
  { value: "M", label: "NOA" },
  { value: "M", label: "PROVINCIA" },
  { value: "M", label: "NACIONAL" },
  { value: "T", label: "PLAN TRASPASO" }
];

export const subplanes = ["0", "A", "B", "C", "N", "P", "O"];

export const sucursal = [
  { value: "W", label: "CASA CENTRAL" },
  { value: "L", label: "PALPALA" },
  { value: "R", label: "PERICO" },
  { value: "P", label: "SAN PEDRO" }
];

export const zonas = [
  { value: 4, label: "PERICO NARVAEZ GENARO" },
  { value: 1, label: "OFICINA MUTUAL" },
  { value: 22, label: "QUIROGA, JUAN PABLO (22)" },
  { value: 40, label: "TRUJILLO" },
  { value: 42, label: "GUILLERMO RODRIGUEZ" },
  { value: 41, label: "LUIS LEON" },
  { value: 43, label: "ARANA, PABLO (A.COM)" },
  { value: 3, label: "OFIC. PALPALA" },
  { value: 21, label: "MARIANA GAZQUEZ" },
  { value: 63, label: "RIVADENEIRA" },
  { value: 64, label: "LA MENDIETA" },
  { value: 60, label: "OFICINA SAN PEDRO" },
  { value: 5, label: "PERICO - OFICINA" },
  { value: 15, label: "LEON, LUIS (Palp)" },
  { value: 14, label: "LEON, MARCELO" },
  { value: 39, label: "ARANA, PABLO" },
  { value: 47, label: "NARVAEZ, GENARO" },
  { value: 48, label: "QUIROGA JUAN (NORTE)" },
  { value: 45, label: "CRUZ, ANSELMO" },
  { value: 53, label: "RIVADENEIRA (S.CLARA II)" },
  { value: 23, label: "RODRIGUEZ, GUILLERMO (C.ARIAS)" },
  { value: 69, label: "CHOQUE GUADALUPE" },
  { value: 28, label: "CACHAMBE ALBERTO" }
];

export const parentesco = [
  { value: 1, label: "Conyugue" },
  { value: 2, label: "Hijo" },
  { value: 3, label: "Padre" },
  { value: 4, label: "Otro" }
];
